---
driver:
  name: terraform
  variable_files:
    - terraform_prod.tfvars

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: basic
      backend: local
      attrs_outputs:
        servers_virginia_public: public_dns

platforms:
  - name: terraform

suites:
  - name: default
